#version 430 core

layout(local_size_x = 256) in;

layout(std430, binding = 0) buffer ScanOutput {
    int scan_output[];
};

layout(std430, binding = 1) readonly buffer BlockOffsets {
    int block_offsets[];
};

uniform int uElementCount;

void main() {
    uint index = gl_GlobalInvocationID.x;
    if (index >= uint(uElementCount)) {
        return;
    }

    scan_output[index] += block_offsets[index / 512u];
}
